gems:
  - jekyll-sitemap

# Build settings
kramdown:
    input: GFM
    coderay_line_numbers: nil
    hard_wrap: false

#Site content configuration
javadoc_url: /javadoc_1.5/
javers_current_version: "1.5.0"

url: "http://javers.org"

