gems:
  - jekyll-sitemap

# Build settings
markdown: redcarpet
kramdown:
    input: GFM
    coderay_line_numbers: nil


#Site content configuration
javadoc_url: /javadoc_1.3.0/
javers_current_version: 1.3.11

url: "http://javers.org"

