gems:
  - jekyll-sitemap

# Build settings
kramdown:
    input: GFM
    coderay_line_numbers: nil
    hard_wrap: false

#Site content configuration
javadoc_url: /javadoc_2.0/
javers_current_version: "2.0.3"

url: "http://javers.org"

