gems:
  - jekyll-sitemap

# Build settings
markdown: redcarpet
kramdown:
    input: GFM
    coderay_line_numbers: nil


#Site content configuration
javadoc_url: /javadoc_1.4.0/
javers_current_version: "1.4.0-RC2"

url: "http://javers.org"

